apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: inventory-db
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: default
  storageSize: 800M
  serviceType: LoadBalancer
  highAvailability:
    enabled: false