apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: #updated in runtime
  region: #updated in runtime
managedNodeGroups:
  - name: containerd-ng
    ami: ami-0d82cc82431a571ca
    instanceType: #update in runtime
    overrideBootstrapCommand: #updated in runtime
