apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: #updated in runtime
  region: #updated in runtime
managedNodeGroups:
  - name: containerd-ng
    ami: CHANGE_ME # according to the region you are deploying to via this command
      # aws ssm get-parameter \
      # --name /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id \
      # --region CHANGE_ME \ 
      # --query "Parameter.Value" 
      # --output text
    instanceType: #update in runtime
    overrideBootstrapCommand: #updated in runtime
