apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: sentiment-routes-config
  labels: 
    tsm-scg: sentiment-brownfield
spec:
  service: 
    name: sentiment-api
  routes:
    - predicates:
        - Path=/list-sentiment
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-sentiment/{teamID}/sensor/{sensorID}
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="sentimentCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-api
spec:
  ports:
    - port: 80
      targetPort: 80
