apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-portal
  labels:
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/part-of: mood-portal
spec:
  #source code
  source:
    git:
      url: https://github.com/dektlong/mood-portal
      ref:
        branch: dev #updated in runtime
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
