apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dekt-catalog-info
  description: A catalog for the dekt group
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - dekt-teams.yaml
    - dekt-domain.yaml
    - brownfield-apis.yaml
