#@ load("@ytt:data", "data")
---
namespace: #@ data.values.apps_namespaces.stageProd
targetImagePullSecret: "registry-credentials"
carbonBlack:
  configSecret:
    name: carbonblack-config-secret
metadataStore:
  url: #@ "{}.{}.{}".format("https://metadata-store", data.values.dns.sysSubDomain, data.values.dns.domain)
  caSecret:
    name: store-ca-cert
    importFromNamespace: "" 
  authSecret:
    name: store-auth-token
    importFromNamespace: "" 