apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://gitea.tap.amer.end2end.link/gitea_admin/tap-demos-w07-s041-1639344619.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1


- name: #@ data.values.dbType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.dbType 
        name:  #@ #@ data.values.dbName
    - name: #@ data.values.msgType + "-claim"
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: #@ data.values.msgType
        name:  #@ data.values.msgName
    - name: #@ data.values.cacheType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.cacheType 
        name:  #@ #@ data.values.cacheName