apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-api
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web-backend

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source-template 

    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: source-scanner-template
      sources:
        - resource: source-provider 
          name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-template
      params:
        - name: image_prefix
          value: dektlong
      sources:
        - resource: source-scanner
          name: scanned-source

    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: image-scanner-template
      images:
        - resource: image-builder
          name: image

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: deliverable-template
      images:
        - resource: image-builder
          name: image