
dev-cluster: # TAP full profile installed
  provider:  #acceptable values: aks, eks, minikube
  nodes:  #see https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-prerequisites.html#resource-requirements-4
  name: ""
stage-cluster: # TAP build profile installed
  provider:  #acceptable values: aks, eks
  nodes:  #see https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-prerequisites.html#resource-requirements-4
  name: ""
prod-cluster: # TAP run profile installed
  provider: #acceptable values: aks, eks
  nodes:  #see https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-prerequisites.html#resource-requirements-4
  name: ""
heritage-cluster: #for bronwfield apis demo, TSM agent installed, no TAP installed
  provider:  #acceptable values: aks, eks
  nodes:  #see https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/services/tanzu-service-mesh-environment-requirements-and-supported-platforms/GUID-D0B939BE-474E-4075-9A65-3D72B5B9F237.html
  name: ""

tap:
  version: "1.1.0"
  systemRepo: ""
  appRepo: ""
  appNamespace: ""

dns:
  domain: ""
  godaddyApiKey: ""
  godaddyApiSecret: ""

apis:
  scgwInstallDirectory: ""
