
provider: # Set at runtime via user input , accepted values: aks, eks, tkg, minikube

clusters:
  devClusterName: ""
  stageClusterName: ""
  prodClusterName: ""

tap:
  version: "1.1.0"
  systemRepo: ""
  appRepo: ""
  appNamespace: ""

dns:
  domain: ""
  godaddyApiKey: ""
  godaddyApiSecret: ""

apis:
  scgwInstallDirectory: ""
