#==================================================================
# Clusters definitions
#
# Supported k8s providers: aks, eks, gke, tkg, minikube
#
# see resource requirements:
#   https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-prerequisites.html#resource-requirements-4
#   https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/services/tanzu-service-mesh-environment-requirements-and-supported-platforms/GUID-D0B939BE-474E-4075-9A65-3D72B5B9F237.html
#==================================================================
view-cluster: # TAP view profile installed
  name: ""
  provider:  
  nodes:
dev-cluster: # TAP iterate profile installed
  name: ""
  provider:  
  nodes:  
stage-cluster: # TAP build profile installed
  name: ""
  provider:  
  nodes:  
prod-cluster: # TAP run profile installed
  name: ""
  provider: 
  nodes:  
brownfield-cluster: #TSM and Spring Cloud Gatewat installed (no TAP)
  name: ""
  provider:  
  nodes: 

#==================================================================
# Configs
#==================================================================
tap:
  version: "" # e.g. 1.1.1
  systemRepo: "" # e.g. dekt-system
  appRepo: "" # e.g. dekt-apps
  appNamespace: "" # e.g. dekt-apps
  prodAuditFile: "" # e.g audit-prod.log, will be created in the .gitops folder
dns:
  domain: "" # e.g. dekt.io
  godaddyApiKey: ""
  godaddyApiSecret: ""
apis:
  scgwInstallDirectory: "" # relative to the dekt-dev-demo root directory
