
dev-cluster:
  provider:  #acceptable values: aks, eks, tkg, minikube
  name: ""
stage-cluster:
  provider:  #acceptable values: aks, eks, tkg
  name: ""
prod-cluster:
  provider:  #acceptable values: aks, eks, tkg
  name: ""

tap:
  version: "1.1.0"
  systemRepo: ""
  appRepo: ""
  appNamespace: ""

dns:
  domain: ""
  godaddyApiKey: ""
  godaddyApiSecret: ""

apis:
  scgwInstallDirectory: ""
