#==================================================================
# TAP Profiles
#   accepted values: full, dev-light, shared-tools, operator-light
#==================================================================
profile: full

#==================================================================
# Build Service
#==================================================================
buildservice:
  kp_default_repository: "$IMAGE_REGISTRY_HOST/$SYSTEM_REPO/build-service"
  kp_default_repository_username: ""
  kp_default_repository_password: ""
  tanzunet_username: ""
  tanzunet_password: ""
  descriptor_name: "tap-1.0.0-full"
  enable_automatic_dependency_updates: true
  
#==================================================================
# Supply Chains
#   accepted values: basic , testing , testing_scanning
#==================================================================
supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "$IMAGE_REGISTRY_HOST"
    repository: "$APP_REPO"
  gitops:
    ssh_secret: ""

ootb_supply_chain_testing:
  registry:
    server: "$IMAGE_REGISTRY_HOST"
    repository: "$APP_REPO"
  gitops:
    ssh_secret: ""

ootb_supply_chain_testing_scanning:
  registry:
    server: "$IMAGE_REGISTRY_HOST"
    repository: "$APP_REPO"
  gitops:
    ssh_secret: ""

#==================================================================
# TAP GUI (Backstage)
#==================================================================
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "sys.$DOMAIN"
  app_config:
    app:
      baseUrl: http://tap-gui.sys.$DOMAIN
    catalog:
      locations:
        - type: url
          target: https://github.com/tanzu-demo/tap-gui-catalogs/blob/main/blank/catalog-info.yaml
        - type: url
          target: https://github.com/dektlong/dekt-supplychain/blob/main/backstage/catalog-info.yaml
    backend:
        baseUrl: http://tap-gui.sys.$DOMAIN
        cors:
            origin: http://tap-gui.sys.$DOMAIN

metadata_store:
  app_service_type: LoadBalancer

cnrs:
  domain_template: "{{.Name}}.{{.Domain}}"
  domain_name: "apps.$DOMAIN"

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  server:
    service_type: "ClusterIP"

grype:
  namespace: "$APP_NS"
  targetImagePullSecret: "registry-credentials"

ceip_policy_disclosed: true

learningcenter:
  ingressDomain: learningcenter.sys.$DOMAIN

