---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db
type: Opaque
stringData:
  type: postgresql
  provider: azure
  host: CHANGE_ME
  port: "1433"
  database: "inventory-db"
  username: "CHANGE_ME"
  password: "CHANGE_ME"