---
#crossplane
apiVersion: bindable.database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: inventory-db-crossplane
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  publishConnectionDetailsTo:
    name: inventory-db
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: rds-postgres
#k8s secret
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db
type: Opaque
stringData:
  type: postgresql
  provider: aws
  host: CHANGE_ME
  port: "5432"
  database: "inventory-db"
  username: "CHANGE_ME"
  password: "CHANGE_ME"