apiVersion: v1
kind: Secret
metadata:
 name: gitops-credentials
 annotations:
  tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
 password: CHANGE_ME
 username: CHANGE_ME