apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: datacheck-apis
  description: APIs to interact with the users data check systems
spec:
  type: openapi
  lifecycle: integration
  owner: dekt-app-ops
  system: brownfield-apis
  definition: |
    $text: http://scg-openapi.sys.dekt.io/openapi